#########################################################################
#                                                                       #
#   PartitionFinder Hydra Submission                                    #
#   25 Feb 2014                                                         #
#   Matthew Kweskin                                                    #
#                                                                       #
#########################################################################

##################
#  


####################################################
#                                                  #
#  Configure this section for your job             #
#  Make sure to preserve spacing used in examples  #
#                                                  #
####################################################

##################
#  Choose PartitionFinder or PartitionFinderProtein
#  Enter 'PartitionFinder.py' for nucleotide or 'PartitionFinderProtein.py' for AA

PFVERSION='PartitionFinder.py'


##################
#  Enter the name of your .cfg file here

CFGFILE='partition_finder.cfg'


##################
#  Additional command line option for PartitionFinder
#  E.g. --raxml  Please don't include -p here, that will be entered for you.

CMDOPTIONS=''


##################
#  Enter the number of CPUs to use after "#$ -pe openmp "
#  
#  All CPUs must be on one server. See: https://www.cfa.harvard.edu/twiki/bin/view/HPC/HPCPrimerConfig
#  for the number of CPUs available on the cluster. As of 17 Apr 2013 there are up to 64
#  CPUs available on a single server.

#$ -pe openmp 16


##################
#  Which Hydra queue to run on.
#  https://www.cfa.harvard.edu/twiki/bin/view/HPC/HPCPrimerQueues#Queues
#    sTN.q (max for is 3 hours, up to 768 CPUs used at once)
#    mTN.q (max is 36 hours, up to 384 CPUs at once)
#    lTN.q (max is 18 days, up to 192 CPUs at once)
#    vTN.q (max is 108 days, up to 98 CPUs at once)

#$ -q lTN.q


##################
#  Email address to be notified on job completion (or termination)

#$ -M email@yourdomain


##################
#  (optional)
#  Enter a name for this job that will appear in the cluster status
#  (make sure there're no spaces in your job name)

#$ -N PartitionFinder


##############################
#                            #
#  DO NOT CHANGE BELOW HERE  #
#                            #
##############################

#$ -S /bin/sh
#$ -V
#$ -e job.err
#$ -o job.out
#$ -cwd
#$ -m aes

source /pool/cluster1/kweskinm/erickson/virtualenv/py2.7.3/bin/activate

python /share/apps/NMNH/PartitionFinder/$PFVERSION -p $NSLOTS $CMDOPTIONS $CFGFILE
